name: private_sync

environment:
  sdk: '^3.4.0'

dependencies:
  args: ^2.5.0
  dartssh2: ^2.8.2
  file: ^7.0.0
  mockito: ^5.4.4
  test: ^1.25.8
  
  collection: any
dev_dependencies:
  build_runner: ^2.4.11
  lints: ^4.0.0
